// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dulce.Facil.Infraestructura.AccesoDatos;

public partial class Sistema_PedidosContext : DbContext
{
    public Sistema_PedidosContext()
    {
    }

    public Sistema_PedidosContext(DbContextOptions<Sistema_PedidosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CLIENTE> CLIENTEs { get; set; }

    public virtual DbSet<DETALLE_PEDIDO> DETALLE_PEDIDOs { get; set; }

    public virtual DbSet<ENTREGA> ENTREGAs { get; set; }

    public virtual DbSet<PEDIDO> PEDIDOs { get; set; }

    public virtual DbSet<PRODUCTO> PRODUCTOs { get; set; }

    public virtual DbSet<RUTA_ENTREGA> RUTA_ENTREGAs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-OOU6HUV7;Initial Catalog=Sistema_Pedidos;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CLIENTE>(entity =>
        {
            entity.HasKey(e => e.id_cliente).HasName("PK__CLIENTE__677F38F55CA78072");

            entity.ToTable("CLIENTE");

            entity.Property(e => e.apellido)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.direccion).HasMaxLength(150);
            entity.Property(e => e.email).HasMaxLength(100);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.telefono).HasMaxLength(20);
        });

        modelBuilder.Entity<DETALLE_PEDIDO>(entity =>
        {
            entity.HasKey(e => e.id_detalle).HasName("PK__DETALLE___4F1332DE6DD97514");

            entity.ToTable("DETALLE_PEDIDO");

            entity.HasIndex(e => e.id_pedido, "IX_DETALLE_PEDIDO");

            entity.HasIndex(e => e.id_producto, "IX_DETALLE_PRODUCTO");

            entity.Property(e => e.subtotal).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_pedidoNavigation).WithMany(p => p.DETALLE_PEDIDOs)
                .HasForeignKey(d => d.id_pedido)
                .HasConstraintName("FK_DETALLE_PEDIDO");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.DETALLE_PEDIDOs)
                .HasForeignKey(d => d.id_producto)
                .HasConstraintName("FK_DETALLE_PRODUCTO");
        });

        modelBuilder.Entity<ENTREGA>(entity =>
        {
            entity.HasKey(e => e.id_entrega).HasName("PK__ENTREGA__017C2C8A17AECF48");

            entity.ToTable("ENTREGA");

            entity.HasIndex(e => e.id_ruta, "IX_ENTREGA_RUTA");

            entity.HasIndex(e => e.id_pedido, "UQ__ENTREGA__6FF01488CC26D2EC").IsUnique();

            entity.Property(e => e.estado_entrega)
                .HasMaxLength(50)
                .HasDefaultValue("Programada");

            entity.HasOne(d => d.id_pedidoNavigation).WithOne(p => p.ENTREGA)
                .HasForeignKey<ENTREGA>(d => d.id_pedido)
                .HasConstraintName("FK_ENTREGA_PEDIDO");

            entity.HasOne(d => d.id_rutaNavigation).WithMany(p => p.ENTREGAs)
                .HasForeignKey(d => d.id_ruta)
                .HasConstraintName("FK_ENTREGA_RUTA");
        });

        modelBuilder.Entity<PEDIDO>(entity =>
        {
            entity.HasKey(e => e.id_pedido).HasName("PK__PEDIDO__6FF01489AD818A39");

            entity.ToTable("PEDIDO");

            entity.HasIndex(e => e.id_cliente, "IX_PEDIDO_CLIENTE");

            entity.Property(e => e.estado)
                .HasMaxLength(50)
                .HasDefaultValue("Pendiente");
            entity.Property(e => e.fecha).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.id_clienteNavigation).WithMany(p => p.PEDIDOs)
                .HasForeignKey(d => d.id_cliente)
                .HasConstraintName("FK_PEDIDO_CLIENTE");
        });

        modelBuilder.Entity<PRODUCTO>(entity =>
        {
            entity.HasKey(e => e.id_producto).HasName("PK__PRODUCTO__FF341C0DDA5DC90E");

            entity.ToTable("PRODUCTO");

            entity.Property(e => e.categoria).HasMaxLength(50);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.precio).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.stock).HasDefaultValue(0);
        });

        modelBuilder.Entity<RUTA_ENTREGA>(entity =>
        {
            entity.HasKey(e => e.id_ruta).HasName("PK__RUTA_ENT__33C9344F9C67E4E5");

            entity.ToTable("RUTA_ENTREGA");

            entity.Property(e => e.direccion)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.nombre_repartidor)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}