// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulce.Facil.Infraestructura.AccesoDatos;

public partial class CLIENTE
{
    public int id_cliente { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string email { get; set; }

    public virtual ICollection<PEDIDO> PEDIDOs { get; set; } = new List<PEDIDO>();
}