// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulce.Facil.Infraestructura.AccesoDatos;

public partial class DETALLE_PEDIDO
{
    public int id_detalle { get; set; }

    public int id_pedido { get; set; }

    public int id_producto { get; set; }

    public int cantidad { get; set; }

    public decimal subtotal { get; set; }

    public virtual PEDIDO id_pedidoNavigation { get; set; }

    public virtual PRODUCTO id_productoNavigation { get; set; }
}