// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulce.Facil.Infraestructura.AccesoDatos;

public partial class PRODUCTO
{
    public int id_producto { get; set; }

    public string nombre { get; set; }

    public string categoria { get; set; }

    public decimal? precio { get; set; }

    public int? stock { get; set; }

    public virtual ICollection<DETALLE_PEDIDO> DETALLE_PEDIDOs { get; set; } = new List<DETALLE_PEDIDO>();
}