// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulce.Facil.Infraestructura.AccesoDatos;

public partial class RUTA_ENTREGA
{
    public int id_ruta { get; set; }

    public DateOnly fecha_entrega { get; set; }

    public string direccion { get; set; }

    public string nombre_repartidor { get; set; }

    public virtual ICollection<ENTREGA> ENTREGAs { get; set; } = new List<ENTREGA>();
}